services:
  mysqldb:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: backerydb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  backend:
    image: 2300090029/docker-bakery-backend:latest
    container_name: springboot
    ports:
      - "2025:2000"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      -springboot-mysql-net

  frontend:
    image: 2300090029/docker-bakery-frontend:latest
    container_name: react
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql-data:

networks:
  springboot-mysql-net:
